In [2]:
import numpy as np

In [ ]:
'''
x_offset = 0
bias = np.array([1, 0]).reshape(-1, 1)
for x in range(result.shape[1]):
    y_offset = 0
    for y in range(result.shape[2]):
        X_dot_W = pic[None, :, x_offset:filter_size + x_offset, y_offset:filter_size + y_offset] * w
        result[:, x, y:y + 1] = np.expand_dims(np.sum(X_dot_W, axis=1).sum(axis=1).sum(axis=1), axis=1) + bias
        y_offset += stride
    x_offset += stride
    
pp(result)
'''

In [3]:
def fmt_item(lines, max_lines=0):
    max_width = max([len(line) for line in lines])
    empty = ' ' * max_width
    lines = [line.ljust(max_width) for line in lines]
    lines += [empty] * (max_lines - len(lines))
    return lines

def pp(*lst):
    lines = [str(item).split('\n') for item in lst]
    max_lines = max([len(item) for item in lines])
    lines = [fmt_item(item, max_lines=max_lines) for item in lines]
    lines_t = np.array(lines).T
    print('\n'.join([' '.join(line) for line in lines_t]))

In [4]:
X = np.array([[9, 9, 9, 9, 9, 9, 9, 9, 9], [0.5, 1, 0.5, 0, 0, 0.5, 1, 1, 0]]).reshape(2, 3, 3)
W = np.array([[-1, 1, -1, 1], [2, -1, 0, -1], [0, 2, 1 ,1], [0, 1, 0, 1]]).reshape(2, 2, 2, 2)
# result = np.zeros((2, 2, 2))
# print(X)
# print(X[:, 0:2, 0:2])
result = np.array([[1, 2, 3, 4], [5, 6, 7, 8]]).reshape(2, 2, 2)
print(result[:, 0, 0])
print(result[:, :, 0])
out_height = result.shape[1]
out_width = result.shape[2]

for y in range(out_height):
    for x in range(out_width):
        pass

# pp(a[0])

[1 5]
[[1 3]
 [5 7]]


In [61]:
w = np.array([[0, 1, 1, 1, -1, 0, -1, 0, 0], [1, 0, 0, -1, 1, -1, -1, -1, 1], [-1, 0, -1, 1, 0, 0, 0, -1, -1],
                [1, 1, -1, 0, 0, 1, -1, 1, 1], [-1, 0, -1, -1, 1, 1, 1, 0, -1], [1, 0, 0, 0, -1, 0, 1, 1, 0]]).reshape(3, 3, 3, 2)
flat_w = w.flatten().flatten().reshape(w.shape[3], -1)
print(flat_w.shape)

(2, 27)


In [62]:

pic_1 = [ 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 1, 1, 0, 0,
          0, 0, 0, 0, 1, 1, 0,
          0, 2, 0, 1, 0, 0, 0,
          0, 2, 1, 2, 2, 0, 0,
          0, 2, 1, 2, 0, 2, 0,
          0, 0, 0, 0, 0, 0, 0 ]

pic_2 = [ 0, 0, 0, 0, 0, 0, 0,
          0, 0, 1, 0, 0, 1, 0,
          0, 1, 2, 1, 1, 2, 0,
          0, 0, 0, 1, 2, 1, 0,
          0, 0, 2, 0, 2, 0, 0,
          0, 2, 2, 2, 0, 2, 0,
          0, 0, 0, 0, 0, 0, 0 ]

pic_3= [ 0, 0, 0, 0, 0, 0, 0,
         0, 1, 1, 1, 1, 1, 0,
         0, 1, 1, 2, 0, 1, 0,
         0, 2, 0, 2, 2, 0, 0,
         0, 0, 0, 1, 0, 1, 0,
         0, 2, 1, 0, 2, 0, 0,
         0, 0, 0, 0, 0, 0, 0 ]

pic = np.array([pic_1, pic_2, pic_3]).reshape(3, 7, 7)
result = np.zeros((2, 3, 3))


filter_size = 3
stride = 2
bias = np.array([1, 0])

x_offset = 0
for x in range(result.shape[1]):
    y_offset = 0
    for y in range(result.shape[2]):
        flat_pic = pic[None, :, x_offset:filter_size + x_offset, y_offset:filter_size + y_offset].flatten()
        X_dot_W = np.dot(flat_w, flat_pic)
        result_shape = result[:, x, y:y + 1].shape
        result[:, x, y:y + 1] = (X_dot_W + bias).reshape(result_shape)
        y_offset += stride
    x_offset += stride
    
pp(result)

[[[-1. -4. -1.]  
  [ 0. -1. -1.]  
  [ 2.  7.  5.]] 
                 
 [[-1.  4.  2.]  
  [-3.  2.  1.]  
  [ 2. -3.  2.]]]


In [75]:
w = np.array([[0, 1, 1, 1, -1, 0, -1, 0, 0], [1, 0, 0, -1, 1, -1, -1, -1, 1], [-1, 0, -1, 1, 0, 0, 0, -1, -1],
                [1, 1, -1, 0, 0, 1, -1, 1, 1], [-1, 0, -1, -1, 1, 1, 1, 0, -1], [1, 0, 0, 0, -1, 0, 1, 1, 0]]).reshape(3, 3, 3, 2)
flat_w = w.flatten().flatten().reshape(w.shape[3], -1)
print(flat_w.shape)

(27, 2)


In [107]:
pic_1 = [ 0, 0, 0, 0, 0, 0, 0,
          0, 0, 0, 1, 1, 0, 0,
          0, 0, 0, 0, 1, 1, 0,
          0, 2, 0, 1, 0, 0, 0,
          0, 2, 1, 2, 2, 0, 0,
          0, 2, 1, 2, 0, 2, 0,
          0, 0, 0, 0, 0, 0, 0 ]

pic_2 = [ 0, 0, 0, 0, 0, 0, 0,
          0, 0, 1, 0, 0, 1, 0,
          0, 1, 2, 1, 1, 2, 0,
          0, 0, 0, 1, 2, 1, 0,
          0, 0, 2, 0, 2, 0, 0,
          0, 2, 2, 2, 0, 2, 0,
          0, 0, 0, 0, 0, 0, 0 ]

pic_3= [ 0, 0, 0, 0, 0, 0, 0,
         0, 1, 1, 1, 1, 1, 0,
         0, 1, 1, 2, 0, 1, 0,
         0, 2, 0, 2, 2, 0, 0,
         0, 0, 0, 1, 0, 1, 0,
         0, 2, 1, 0, 2, 0, 0,
         0, 0, 0, 0, 0, 0, 0 ]

pic = np.array([[pic_1, pic_2, pic_3], [pic_1, pic_2, pic_3]]).reshape(2, 7, 7, 3)
result = np.zeros((2, 3, 3, 2))

batch_size = 2
filter_size = 3
stride = 2
bias = np.array([1, 0])

x_offset = 0
for x in range(result.shape[1]):
    y_offset = 0
    for y in range(result.shape[2]):
        flat_pic = pic[:, x_offset:filter_size + x_offset, y_offset:filter_size + y_offset, :].flatten().reshape(batch_size, flat_w.shape[0])
        X_dot_W = np.dot(flat_pic, flat_w)
        result_shape = result[:, x, y:y + 1, :].shape
        result[:, x, y:y + 1, :] = (X_dot_W + bias).reshape(result_shape)
        y_offset += stride
    x_offset += stride
    
pp(result)

[[[[ 1.  3.]   
   [ 1.  0.]   
   [ 1. -3.]]  
               
  [[ 3. -1.]   
   [ 2. -1.]   
   [-3.  2.]]  
               
  [[ 2.  3.]   
   [ 2.  3.]   
   [ 2. -4.]]] 
               
               
 [[[ 1.  3.]   
   [ 1.  0.]   
   [ 2. -4.]]  
               
  [[ 0.  1.]   
   [ 1.  0.]   
   [ 0. -1.]]  
               
  [[ 6.  8.]   
   [ 3.  0.]   
   [-1. -2.]]]]
